### ISSUE TITLE
Add missing API methods

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-jupyter#148]
The following module methods are not documented:

1. G2Config
    1. getLastExceptionCode
1. G2ConfigMgr
    1. getLastExceptionCode
    1. replaceDefaultConfigID
1. G2Engine
    1. addRecordWithInfoWithReturnedRecordID
    1. checkRecord
    1. clearLastException
    1. findInterestingEntitiesByEntityID
    1. findInterestingEntitiesByRecordID
    1. getLastException
    1. getLastExceptionCode
    1. getVirtualEntityByRecordID
    1. processWithResponse

The following searches verify this:

1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=addRecordWithInfoWithReturnedRecordID
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=checkRecord
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=clearLastException
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=findInterestingEntitiesByEntityID
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=findInterestingEntitiesByRecordID
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=getLastException
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=getLastExceptionCode
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=getVirtualEntityByRecordID
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=processWithResponse
1. https://github.com/Senzing/senzing-sdk-api-specification/search?q=replaceDefaultConfigID

**Comment by docktermj** [comment]
Full list, but may not all be documented:

1. **G2Config**
    1. getLastExceptionCode
1. **G2ConfigMgr**
    1. replaceDefaultConfigID
    1. getLastExceptionCode
1. **G2Diagnostic**
    1. checkDBPerf
    1. clearLastException
    1. closeEntityListBySize
    1. destroy
    1. fetchNextEntityBySize
    1. findEntitiesByFeatureIDs
    1. getAvailableMemory
    1. getDataSourceCounts
    1. getDBInfo
    1. getEntityDetails
    1. getEntityListBySize
    1. getEntityResume
    1. getEntitySizeBreakdown
    1. getFeature
    1. getGenericFeatures
    1. getLastException
    1. getLastExceptionCode
    1. getLogicalCores
    1. getMappingStatistics
    1. getPhysicalCores
    1. getRelationshipDetails
    1. getResolutionStatistics
    1. getTotalSystemMemory
    1. init
    1. initWithConfigID
    1. reinit
1. **G2Engine**
    1. clearLastException
    1. getLastException
    1. getLastExceptionCode
    1. processWithResponse
    1. checkRecord
    1. addRecordWithInfoWithReturnedRecordID
    1. getVirtualEntityByRecordID
    1. findInterestingEntitiesByEntityID
    1. findInterestingEntitiesByRecordID
1. **G2Hasher**
    1. clearLastException
    1. destroy
    1. exportTokenLibrary
    1. getLastException
    1. getLastExceptionCode
    1. init
    1. initWithConfig
    1. process
    1. reportHasherNotIncluded
1. **G2IniParams**
    1. getINIParam
    1. getJsonINIParams
    1. hasINIParam
    1. removeINIParam
1. **G2Product**
    1. clearLastException
    1. destroy
    1. getLastException
    1. getLastExceptionCode
    1. init
    1. license
    1. validateLicenseFile
    1. validateLicenseStringBase64
    1. version

**Comment by SamMacy** [comment]
Work being done in [senzing-sdk-api-specification](https://github.com/Senzing/senzing-sdk-api-specification/issues/25)
