### ISSUE TITLE
Major updates to G2Engine() docs for python

### ISSUE THREAD

**Issue by SamMacy** [Senzing/docker-jupyter#55]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/docker-jupyter/pull/58
2. https://github.com/Senzing/docker-jupyter/pull/59

**Comment by docktermj** [comment]
A pull request that was not pulled into master:

https://github.com/Senzing/docker-jupyter/pull/56
