### ISSUE TITLE
Add example for the new "why" functions

### ISSUE THREAD

**Issue by SamMacy** [Senzing/docker-jupyter#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by docktermj** [comment]
Pull requests:

1. https://github.com/Senzing/docker-jupyter/pull/60

**Comment by docktermj** [comment]
A pull request that was not pulled into master:

https://github.com/Senzing/docker-jupyter/pull/56
