### ISSUE TITLE
404 error on developer page

### ISSUE THREAD

**Issue by jiportilla** [Senzing/docker-jupyter#71]
**Describe the bug**
404 error to jupyter notebook on the developer page
https://github.com/Senzing/docker-jupyter/blob/master/notebooks/senzing-examples/python/senzing-G2Engine.ipynb

**To Reproduce**
navigate to 
https://senzing.com/releases/

In this paragraph , the first link does not work *** here****
Version: 1.13.1
Released: 25 Nov 2019

Added new whyEntity set of functions to describe why records are part of an entity. Find documentation ****here ******and jupyter notebooks here and here.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by docktermj** [comment]
Hi @jiportilla!   Thanks for reporting the issue.

@antaenc, @brianmacy  On https://senzing.com/releases/ in the Version 1.13.1 section, the "Jupyter notebooks here" link is broken.   It should point to https://github.com/Senzing/docker-jupyter/blob/master/notebooks/senzing-examples/python/senzing-G2Engine-reference.ipynb

You had the URL correct initially.   I changed the filename from "senzing-G2Engine.ipynb" to "senzing-G2Engine-reference.ipynb" 2 weeks ago in https://github.com/Senzing/docker-jupyter/issues/61 to identify the python notebook as a "Reference".   This is to distinguish it from the other Python Notebooks which are "Guides".   ("References" are like dictionaries;  "Guides" are step-by-step instructions that "point" to the "Reference" when more details are needed.  This approach keeps "Guides" cleaner and avoids duplicate information.)

I didn't realize that the notebook URL was referenced externally.   My apologies.

**Comment by docktermj** [comment]
@jiportilla We've corrected the link.  If it works to your satisfaction please close this issue.  If not, please let us know how to improve the experience.

If we don't hear back in a week, we'll close the issue for you.

**Comment by jiportilla** [comment]
works as intended, closing this issue.
