### ISSUE TITLE
addDatasource seems to be missing

### ISSUE THREAD

**Issue by brianmacy** [Senzing/docker-jupyter#76]
docs.senzing.com documents addDatasource but it is missing from this notebook

**Comment by docktermj** [comment]
@brianmacy  Which notebook?  

It is shown in https://github.com/Senzing/docker-jupyter/blob/master/notebooks/senzing-examples/python/senzing-G2Config-addDataSource.ipynb

But it is missing in https://github.com/Senzing/docker-jupyter/blob/master/notebooks/senzing-examples/python/senzing-G2Config-reference.ipynb and should be included in the **-reference.ipynb** and should be included in that notebook.

**Comment by brianmacy** [comment]
It is missing from the reference which means the function description is missing and the non-reference which links to it finds nothing.


Brian Macy
Senzing, Director of Product Development and Operations
brian@senzing.com<mailto:brian@senzing.com>

Follow Senzing on Website<http://www.senzing.com/> | Twitter<https://twitter.com/senzing> | LinkedIn<https://www.linkedin.com/company/senzing-inc/> | Facebook<https://www.facebook.com/senzinginc/>
Follow me on LinkedIn<https://www.linkedin.com/in/brianmacy/>

If you are not an intended recipient of confidential and privileged information in this email, please delete it, notify the sender immediately, and do not use or disseminate such information.

On Jan 11, 2020, 12:16 -0500, Michael Dockter <notifications@github.com>, wrote:

@brianmacy<https://github.com/brianmacy> Which notebook?

It is shown in https://github.com/Senzing/docker-jupyter/blob/master/notebooks/senzing-examples/python/senzing-G2Config-addDataSource.ipynb

But it is missing in https://github.com/Senzing/docker-jupyter/blob/master/notebooks/senzing-examples/python/senzing-G2Config-reference.ipynb and should be included in the -reference.ipynb and should be included in that notebook.

**Comment by docktermj** [comment]
We're on the same page.  The new information needs to be added to https://github.com/Senzing/docker-jupyter/blob/master/notebooks/senzing-examples/python/senzing-G2Config-reference.ipynb   (and the corresponding Java G2Config reference).

**Comment by SamMacy** [comment]
Completed
