### ISSUE TITLE
Add nbextensions

### ISSUE THREAD

**Issue by SamMacy** [Senzing/docker-jupyter#90]
Add ipynb extensions to allow for all sorts of new goodies, but also add in automatically generated table of contents.

**Comment by docktermj** [comment]
Pull Requests:

1. https://github.com/Senzing/docker-jupyter/pull/92
2. https://github.com/Senzing/docker-jupyter/pull/93
3. https://github.com/Senzing/docker-jupyter/pull/94
4. https://github.com/Senzing/docker-jupyter/pull/95
